### ISSUE TITLE
How can i custom the -c options?

### ISSUE THREAD

**Issue by AntetokounmJie** [moold/ParallelTask#1]
Hi sir

I try to use ParallelTask to manage my jobs on a sge system.
When i want to custom the -c option just like " -cwd -l vf=16g,p=8 -q node-4", the error came up.
My command is “python ~/ParallelTask-master/main.py -t sge -m 10 -c '[-l vf=16g,p=8 -q cn-4]' command.sh”
And i try some other ways to pass the -c option to main.py, but the error still there.
So, how can i custom the -c options correctly?

Thanks a lot 
:)

**Comment by moold** [comment]
Try `-c " -l vf={vf} -pe smp {cpu} -S {bash} -w n -q all.q"`, if you still have problem, check your SGE configuration.
